pub const ANDROID_WEBVIEW_CLIENT: &str = "android-webview";
const ANDROID_WEBVIEW_INITIAL_LAYOUT_ATTRS: &str =
    " data-layout-client=\"android-webview\" data-layout-shape=\"tablet_portrait\"";

pub fn render_webui_smoke() -> String {
    render_webui_smoke_for_client(None)
}

pub fn render_webui_smoke_for_client(client: Option<&str>) -> String {
    let initial_body_attrs = initial_layout_body_attrs(client);
    let initial_shell_attrs = initial_layout_shell_attrs(client);
    format!(
        concat!(
            "<!DOCTYPE html>",
            "<html lang=\"zh-CN\">",
            "<head>",
            "<meta charset=\"UTF-8\" />",
            "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, viewport-fit=cover\" />",
            "<title>Freehand WebUI</title>",
            "<link rel=\"stylesheet\" href=\"/assets/theme.css\" />",
            "<link rel=\"stylesheet\" href=\"/assets/webui.css\" />",
            "</head>",
            "<body class=\"theme-light\"{}>",
            "<main class=\"app-shell\" data-webui-shell=\"true\"{} ",
            "data-adp-endpoint=\"/adp\" ",
            "data-turn-query=\"/ui/query/latest-active-turn\" ",
            "data-turn-subscribe=\"/ui/subscribe/turn/latest\" ",
            "data-debug-query-base=\"/ui/query/debug/\" ",
            "data-debug-subscribe-base=\"/ui/subscribe/debug/\" ",
            "data-checkpoint-query=\"/ui/query/checkpoints\" ",
            "data-command-endpoint=\"/ui/command\" ",
            "data-selected-session=\"\" ",
            "data-selected-turn=\"\">",
            "<div class=\"mobile-drawer-scrim\" id=\"mobile-drawer-scrim\" aria-hidden=\"true\"></div>",
            "<aside class=\"rail\">",
            "<div class=\"brand\">FH</div>",
            "<div class=\"rail-group\">",
            "<button class=\"rail-button active\" type=\"button\">WS</button>",
            "<button class=\"rail-button\" type=\"button\">ND</button>",
            "<button class=\"rail-button\" type=\"button\">RP</button>",
            "<button class=\"rail-button\" type=\"button\">DG</button>",
            "</div>",
            "</aside>",
            "<aside class=\"sidebar\">",
            "<div class=\"drawer-panel-head\">",
            "<div><div class=\"eyebrow\">sessions</div><h1 class=\"page-title\">Sessions</h1></div>",
            "<button class=\"drawer-close-button\" id=\"close-session-drawer-button\" type=\"button\" aria-label=\"Close sessions\">Close</button>",
            "</div>",
            "<label class=\"task-cwd-control\" for=\"task-cwd-input\"><span>Task target directory</span><input id=\"task-cwd-input\" type=\"text\" placeholder=\"/Volumes/extension/code/freehand\" autocomplete=\"off\" /></label>",
            "<div class=\"session-create-actions\">",
            "<button class=\"session-conversation-button\" id=\"new-conversation-button\" type=\"button\">New conversation</button>",
            "<button class=\"session-task-button\" id=\"new-task-button\" type=\"button\">New task</button>",
            "</div>",
            "<div class=\"session-bulk-toolbar\" aria-label=\"Session management\">",
            "<div class=\"session-bulk-summary\"><span class=\"session-bulk-label\">bulk</span><span class=\"session-bulk-count\" id=\"session-bulk-count\">0 selected</span></div>",
            "<div class=\"session-bulk-actions\">",
            "<button class=\"session-bulk-button select-all\" id=\"session-select-all-button\" type=\"button\">Select all</button>",
            "<button class=\"session-bulk-button\" id=\"session-clear-selection-button\" type=\"button\">Clear</button>",
            "<button class=\"session-bulk-button\" id=\"session-rename-selected-button\" type=\"button\" disabled>Rename</button>",
            "<button class=\"session-bulk-button danger\" id=\"session-delete-selected-button\" type=\"button\" disabled>Remove</button>",
            "</div>",
            "</div>",
            "<div class=\"session-list\" id=\"session-list\">",
            "<section class=\"session-item active\"><div class=\"meta-label\">loading</div><div class=\"session-title\" id=\"session-title\">waiting for service state</div><div class=\"session-copy\" id=\"session-copy\">no active turn yet</div></section>",
            "</div>",
            "</aside>",
            "<section class=\"workspace\">",
            "<header class=\"topbar region-card\">",
            "<div class=\"topbar-main\">",
            "<div class=\"mobile-shell-controls\" aria-label=\"Mobile navigation\">",
            "<button class=\"mobile-drawer-button\" id=\"open-session-drawer-button\" type=\"button\" aria-controls=\"session-list\">List</button>",
            "<button class=\"mobile-drawer-button\" id=\"open-detail-drawer-button\" type=\"button\" aria-controls=\"debug-status\">Status</button>",
            "<button class=\"mobile-drawer-button\" id=\"open-settings-drawer-button\" type=\"button\" aria-controls=\"settings-shell\">Config</button>",
            "</div>",
            "<div class=\"topbar-title-wrap\">",
            "<h1 class=\"page-title\">Freehand</h1>",
            "</div>",
            "<div class=\"topbar-actions\">",
            "<button class=\"debug-toggle\" id=\"settings-shell-toggle\" type=\"button\" aria-pressed=\"false\">Settings</button>",
            "<div class=\"theme-toggle\" aria-label=\"Theme switch\">",
            "<button class=\"theme-button is-active\" data-theme=\"light\" type=\"button\">White</button>",
            "<button class=\"theme-button\" data-theme=\"dark\" type=\"button\">Black</button>",
            "</div>",
            "<button class=\"debug-toggle\" id=\"debug-details-toggle\" type=\"button\" aria-pressed=\"false\">Debug details</button>",
            "<span class=\"status-pill ok\" id=\"workspace-status\">booting</span>",
            "</div>",
            "</div>",
            "</header>",
            "<section class=\"conversation-region region-card\">",
            "<div class=\"region-header\">",
            "<div class=\"turn-status\">",
            "<span class=\"status-dot\" id=\"turn-status\">waiting</span>",
            "</div>",
            "</div>",
            "<div class=\"stream-stage\">",
            "<div class=\"message-list autonomous\" id=\"message-list\">",
            "<div class=\"chat-empty-state\"><div class=\"chat-empty-title\">New conversation</div><div class=\"chat-empty-copy\">Send a message to start this session.</div></div>",
            "</div>",
            "</div>",
            "<section class=\"composer-card\">",
            "<form class=\"composer-grid\" id=\"composer-form\">",
            "<textarea class=\"composer-input\" id=\"composer-input\" placeholder=\"输入新的任务或继续当前 turn\"></textarea>",
            "<div class=\"composer-actions\">",
            "<button class=\"button\" id=\"send-button\" type=\"submit\">Send</button>",
            "<button class=\"button secondary\" id=\"cancel-button\" type=\"button\">Cancel</button>",
            "</div>",
            "</form>",
            "<div class=\"composer-control-strip\" aria-label=\"Composer controls\">",
            "<label class=\"control-chip\" id=\"attach-file-button\" for=\"attachment-file-input\" role=\"button\" tabindex=\"0\">加文件</label>",
            "<label class=\"control-chip\" id=\"attach-image-button\" for=\"attachment-image-input\" role=\"button\" tabindex=\"0\">加图片</label>",
            "<label class=\"control-chip\" id=\"attach-video-button\" for=\"attachment-video-input\" role=\"button\" tabindex=\"0\">加视频</label>",
            "<button class=\"control-chip\" id=\"preview-attachments-button\" type=\"button\">预览附件</button>",
            "<button class=\"control-chip\" id=\"refresh-session-button\" type=\"button\">刷新会话</button>",
            "<label class=\"cwd-control\" for=\"cwd-input\"><span>CWD</span><input id=\"cwd-input\" type=\"text\" placeholder=\"/path/to/workspace\" autocomplete=\"off\" /></label>",
            "<label class=\"model-control\" for=\"model-selector\"><span>Model</span><select id=\"model-selector\"><option value=\"runtime\">Runtime config</option></select></label>",
            "<input id=\"attachment-file-input\" type=\"file\" multiple hidden />",
            "<input id=\"attachment-image-input\" type=\"file\" accept=\"image/*\" multiple hidden />",
            "<input id=\"attachment-video-input\" type=\"file\" accept=\"video/*\" multiple hidden />",
            "</div>",
            "<div class=\"attachment-tray\" id=\"attachment-tray\" aria-live=\"polite\"></div>",
            "<div class=\"command-status\" id=\"command-status\">command idle</div>",
            "</section>",
            "</section>",
            "</section>",
            "<dialog class=\"new-session-dialog\" id=\"new-session-dialog\" aria-labelledby=\"new-session-dialog-title\">",
            "<form class=\"new-session-panel\" id=\"new-session-form\" method=\"dialog\">",
            "<div class=\"new-session-head\">",
            "<div><div class=\"eyebrow\">new</div><h2 class=\"new-session-title\" id=\"new-session-dialog-title\">Start work</h2></div>",
            "<button class=\"dialog-close-button\" id=\"new-session-cancel-button\" type=\"button\">Close</button>",
            "</div>",
            "<div class=\"new-session-choice\" role=\"radiogroup\" aria-label=\"New session type\">",
            "<label class=\"new-session-option\"><input type=\"radio\" name=\"new-session-kind\" value=\"conversation\" checked /><span><strong>New session</strong><small>Global conversation</small></span></label>",
            "<label class=\"new-session-option\"><input type=\"radio\" name=\"new-session-kind\" value=\"task\" /><span><strong>New task</strong><small>Choose a target directory</small></span></label>",
            "</div>",
            "<label class=\"new-task-path-control\" for=\"new-session-cwd-input\"><span>Task directory</span><div class=\"new-task-path-row\"><input id=\"new-session-cwd-input\" type=\"text\" placeholder=\"Choose or type a path\" autocomplete=\"off\" /><button class=\"control-chip\" id=\"new-session-browse-button\" type=\"button\">Choose</button></div></label>",
            "<div class=\"new-task-path-presets\" id=\"new-task-path-presets\" aria-label=\"Task directory choices\">",
            "<button class=\"path-preset-button\" type=\"button\" data-cwd=\"/Volumes/extension/code/freehand\">freehand</button>",
            "<button class=\"path-preset-button\" type=\"button\" data-cwd=\"/Volumes/extension/code\">code</button>",
            "<button class=\"path-preset-button\" type=\"button\" data-cwd=\"/Users/fanzhang/code\">~/code</button>",
            "</div>",
            "<div class=\"new-session-actions\">",
            "<button class=\"session-bulk-button\" id=\"new-session-close-button\" type=\"button\">Cancel</button>",
            "<button class=\"session-task-button\" id=\"new-session-confirm-button\" type=\"submit\">Create</button>",
            "</div>",
            "</form>",
            "</dialog>",
            "<aside class=\"inspector\">",
            "<div class=\"drawer-panel-head\">",
            "<div><div class=\"eyebrow\" id=\"inspector-eyebrow\">detail region</div><h2 class=\"inspector-title\" id=\"inspector-title\">Selected Turn Debug</h2></div>",
            "<button class=\"drawer-close-button\" id=\"close-detail-drawer-button\" type=\"button\" aria-label=\"Close details\">Close</button>",
            "</div>",
            "<p class=\"page-copy\" id=\"inspector-copy\">右侧只展示当前 turn 的调试摘要，不抢主消息流焦点。</p>",
            "<div class=\"stack inspector-debug-panel\" id=\"inspector-debug-panel\">",
            "<section class=\"inspector-block\">",
            "<div class=\"meta-label\">debug status</div>",
            "<div class=\"inspector-block-title\" id=\"debug-status\">waiting</div>",
            "<div class=\"inspector-copy\" id=\"debug-lines\">-</div>",
            "</section>",
            "<section class=\"inspector-block checkpoint-block\">",
            "<div class=\"meta-label\">checkpoints</div>",
            "<div class=\"inspector-block-title\" id=\"checkpoint-status\">waiting</div>",
            "<div class=\"checkpoint-list\" id=\"checkpoint-list\">-</div>",
            "</section>",
            "</div>",
            "<div class=\"settings-shell\" id=\"settings-shell\" hidden>",
            "<section class=\"settings-hero\">",
            "<div><div class=\"meta-label\">editable</div><div class=\"settings-hero-title\">Provider config</div></div>",
            "<span class=\"settings-status-pill\" id=\"settings-status-pill\">connecting</span>",
            "</section>",
            "<div class=\"settings-grid\">",
            "<details class=\"settings-card\" open><summary><span>Provider and model</span><span id=\"settings-provider-summary\">loading</span></summary><div class=\"settings-card-body\"><div class=\"settings-row\"><span>Provider</span><strong id=\"settings-provider-id\">loading</strong></div><div class=\"settings-row\"><span>Type</span><strong id=\"settings-provider-type\">loading</strong></div><div class=\"settings-row\"><span>Protocol</span><strong id=\"settings-provider-protocol\">loading</strong></div><div class=\"settings-row\"><span>Host</span><strong id=\"settings-provider-host\">loading</strong></div><div class=\"settings-row\"><span>Model selector</span><strong id=\"settings-model-value\">Runtime config</strong></div><div class=\"settings-row\"><span>Auth source</span><strong id=\"settings-provider-auth\">loading</strong></div><div class=\"settings-row\"><span>Activation</span><strong id=\"settings-restart-required\">loading</strong></div><div class=\"settings-row\"><span>Config status</span><strong id=\"settings-config-error\">none</strong></div><form class=\"settings-provider-form\" id=\"settings-provider-form\"><label><span>Provider id</span><input id=\"settings-provider-id-input\" name=\"provider_id\" autocomplete=\"off\" /></label><label><span>Type</span><select id=\"settings-provider-type-input\" name=\"provider_type\"><option value=\"openai\">OpenAI-compatible</option><option value=\"anthropic\">Anthropic messages</option></select></label><label><span>Protocol</span><select id=\"settings-provider-protocol-input\" name=\"provider_protocol\"><option value=\"responses\">Responses</option><option value=\"chat_completions\">Chat completions</option><option value=\"messages\">Messages</option></select></label><label><span>Endpoint</span><input id=\"settings-provider-url-input\" name=\"base_url\" placeholder=\"https://api.example.com/v1\" autocomplete=\"off\" /></label><label><span>Default model</span><input id=\"settings-provider-model-input\" name=\"default_model\" autocomplete=\"off\" /></label><label><span>Credential env var</span><input id=\"settings-provider-env-input\" name=\"api_key_env\" placeholder=\"PROVIDER_CREDENTIAL\" autocomplete=\"off\" /></label><div class=\"settings-note\" id=\"settings-provider-save-status\">Save validates and writes config; restart is required before active runtime changes.</div><button class=\"settings-primary-action\" id=\"settings-provider-save-button\" type=\"submit\">Save provider config</button></form></div></details>",
            "</div>",
            "</div>",
            "</aside>",
            "</main>",
            "<script type=\"module\" src=\"/assets/webui.js\"></script>",
            "</body>",
            "</html>"
        ),
        initial_body_attrs, initial_shell_attrs
    )
}

fn initial_layout_body_attrs(client: Option<&str>) -> &'static str {
    match client {
        Some(ANDROID_WEBVIEW_CLIENT) => ANDROID_WEBVIEW_INITIAL_LAYOUT_ATTRS,
        _ => "",
    }
}

fn initial_layout_shell_attrs(client: Option<&str>) -> &'static str {
    match client {
        Some(ANDROID_WEBVIEW_CLIENT) => ANDROID_WEBVIEW_INITIAL_LAYOUT_ATTRS,
        _ => "",
    }
}
