pub const ANDROID_WEBVIEW_CLIENT: &str = "android-webview";
const ANDROID_WEBVIEW_INITIAL_LAYOUT_ATTRS: &str =
    " data-layout-client=\"android-webview\" data-layout-shape=\"tablet_portrait\"";

pub fn render_webui_smoke() -> String {
    render_webui_smoke_for_client(None)
}

pub fn render_webui_smoke_for_client(client: Option<&str>) -> String {
    let initial_body_attrs = initial_layout_body_attrs(client);
    let initial_shell_attrs = initial_layout_shell_attrs(client);
    crate::assets::stamp_asset_version(&format!(
        concat!(
            "<!DOCTYPE html>",
            "<html lang=\"zh-CN\">",
            "<head>",
            "<meta charset=\"UTF-8\" />",
            "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, viewport-fit=cover\" />",
            "<title>Freehand 网页界面</title>",
            "<link rel=\"stylesheet\" href=\"assets/theme.css?v=__WEBUI_ASSET_VERSION__\" />",
            "<link rel=\"stylesheet\" href=\"assets/webui.css?v=__WEBUI_ASSET_VERSION__\" />",
            "</head>",
            "<body class=\"theme-light\"{}>",
            "<main class=\"app-shell\" data-webui-shell=\"true\"{} ",
            "data-adp-endpoint=\"adp\" ",
            "data-turn-query=\"ui/query/latest-active-turn\" ",
            "data-turn-subscribe=\"ui/subscribe/turn/latest\" ",
            "data-debug-query-base=\"ui/query/debug/\" ",
            "data-debug-subscribe-base=\"ui/subscribe/debug/\" ",
            "data-checkpoint-query=\"ui/query/checkpoints\" ",
            "data-command-endpoint=\"ui/command\" ",
            "data-selected-session=\"\" ",
            "data-selected-turn=\"\">",
            "<div class=\"mobile-drawer-scrim\" id=\"mobile-drawer-scrim\" aria-hidden=\"true\"></div>",
            "<aside class=\"rail\">",
            "<div class=\"brand\"><img class=\"brand-logo\" src=\"assets/logo.png?v=20260723-logo-refresh\" alt=\"Freehand\" /></div>",
            "<div class=\"rail-group\">",
            "<button class=\"rail-button active\" type=\"button\">WS</button>",
            "<button class=\"rail-button\" type=\"button\">ND</button>",
            "<button class=\"rail-button\" type=\"button\">RP</button>",
            "<button class=\"rail-button\" type=\"button\">DG</button>",
            "</div>",
            "</aside>",
            "<aside class=\"sidebar\">",
            "<div class=\"drawer-panel-head\">",
            "<div><div class=\"eyebrow\">会话</div><h1 class=\"page-title\">会话</h1></div>",
            "<button class=\"drawer-close-button\" id=\"close-session-drawer-button\" type=\"button\" aria-label=\"关闭会话列表\">关闭</button>",
            "</div>",
            "<label class=\"task-cwd-control\" for=\"task-cwd-input\"><span>任务目录</span><input id=\"task-cwd-input\" type=\"text\" placeholder=\"/Volumes/extension/code/freehand\" autocomplete=\"off\" /></label>",
            "<div class=\"session-create-actions\">",
            "<button class=\"session-conversation-button\" id=\"new-conversation-button\" type=\"button\">新建会话</button>",
            "<button class=\"session-task-button\" id=\"new-task-button\" type=\"button\">新建任务</button>",
            "</div>",
            "<div class=\"session-bulk-toolbar\" aria-label=\"会话管理\">",
            "<div class=\"session-bulk-summary\"><span class=\"session-bulk-label\">批量</span><span class=\"session-bulk-count\" id=\"session-bulk-count\">已选 0 个</span></div>",
            "<div class=\"session-bulk-actions\">",
            "<button class=\"session-bulk-button select-all\" id=\"session-select-all-button\" type=\"button\">全选</button>",
            "<button class=\"session-bulk-button\" id=\"session-clear-selection-button\" type=\"button\">清空</button>",
            "<button class=\"session-bulk-button danger\" id=\"session-delete-selected-button\" type=\"button\" disabled>移除</button>",
            "</div>",
            "</div>",
            "<div class=\"session-list\" id=\"session-list\">",
            "<section class=\"session-item active\"><div class=\"meta-label\">加载中</div><div class=\"session-title\" id=\"session-title\">等待服务状态</div><div class=\"session-copy\" id=\"session-copy\">暂无活跃 turn</div></section>",
            "</div>",
            "</aside>",
            "<div class=\"layout-resizer layout-resizer-left\" data-layout-resizer=\"left\" role=\"separator\" aria-orientation=\"vertical\" aria-label=\"调整会话面板宽度\" tabindex=\"0\"></div>",
            "<section class=\"workspace\">",
            "<header class=\"topbar region-card\">",
            "<div class=\"topbar-main\">",
            "<div class=\"mobile-shell-controls\" aria-label=\"移动端快速入口\">",
            "<button class=\"mobile-drawer-button mobile-corner-button mobile-config-entry\" id=\"open-settings-drawer-button\" type=\"button\" aria-label=\"配置\" aria-controls=\"settings-shell\"><svg viewBox=\"0 0 24 24\" aria-hidden=\"true\"><path d=\"M12 8.2a3.8 3.8 0 1 0 0 7.6 3.8 3.8 0 0 0 0-7.6Z\"/><path d=\"M20.4 13.4v-2.8l-2.2-.5a7 7 0 0 0-.7-1.6l1.2-1.9-2-2-1.9 1.2a7 7 0 0 0-1.6-.7L12.8 3h-2.8l-.5 2.2a7 7 0 0 0-1.6.7L6 4.7l-2 2 1.2 1.9a7 7 0 0 0-.7 1.6l-2.2.5v2.8l2.2.5c.2.6.4 1.1.7 1.6L4 17.4l2 2 1.9-1.2c.5.3 1 .5 1.6.7l.5 2.2h2.8l.5-2.2c.6-.2 1.1-.4 1.6-.7l1.9 1.2 2-2-1.2-1.9c.3-.5.5-1 .7-1.6l2.1-.5Z\"/></svg></button>",
            "<div class=\"mobile-top-right-entries\"><button class=\"mobile-drawer-button mobile-corner-button\" id=\"open-timer-dashboard-button\" type=\"button\" aria-label=\"定时任务\"><svg viewBox=\"0 0 24 24\" aria-hidden=\"true\"><circle cx=\"12\" cy=\"12\" r=\"8.5\"/><path d=\"M12 6.8v5.5l3.6 2.2\"/></svg></button><button class=\"mobile-drawer-button mobile-corner-button\" id=\"open-tools-dashboard-button\" type=\"button\" aria-label=\"内置工具\"><svg viewBox=\"0 0 24 24\" aria-hidden=\"true\"><path d=\"M4 6h16v12H4z\"/><path d=\"m8 10 3 2-3 2\"/><path d=\"M13 15h4\"/></svg></button></div>",
            "</div>",
            "<div class=\"topbar-title-wrap\">",
            "<h1 class=\"page-title\">Freehand</h1>",
            "</div>",
            "<div class=\"topbar-actions\">",
            "<button class=\"debug-toggle\" id=\"settings-shell-toggle\" type=\"button\" aria-pressed=\"false\">设置</button>",
            "<div class=\"theme-toggle\" aria-label=\"主题切换\">",
            "<button class=\"theme-button is-active\" data-theme=\"light\" type=\"button\">白色</button>",
            "<button class=\"theme-button\" data-theme=\"dark\" type=\"button\">黑色</button>",
            "</div>",
            "<button class=\"debug-toggle\" id=\"debug-details-toggle\" type=\"button\" aria-pressed=\"false\">调试详情</button>",
            "<span class=\"status-pill ok\" id=\"workspace-status\">启动中</span>",
            "</div>",
            "</div>",
            "<section class=\"session-relation-header\" id=\"session-relation-header\" aria-label=\"当前会话关系\">",
            "<div class=\"session-dashbar-row\">",
            "<button class=\"session-dashbar\" id=\"session-relation-toggle-button\" type=\"button\" aria-expanded=\"false\" aria-controls=\"session-tree-dropdown\">",
            "<span class=\"session-dashbar-kicker\" id=\"session-relation-kicker\">当前会话</span>",
            "<span class=\"session-dashbar-title\" id=\"session-relation-title\">未选择会话</span>",
            "<span class=\"session-dashbar-metrics\" id=\"session-relation-metrics\">0 个任务</span>",
            "<span class=\"session-dashbar-copy\" id=\"session-relation-copy\">点开查看当前会话内容</span>",
            "<span class=\"session-dashbar-chevron\" aria-hidden=\"true\">⌄</span>",
            "</button>",
            "<div class=\"session-detail-actions\" aria-label=\"当前会话操作\"><button class=\"session-detail-rename-button\" id=\"selected-session-rename-button\" type=\"button\" aria-label=\"重命名当前会话\" hidden disabled><svg viewBox=\"0 0 24 24\" aria-hidden=\"true\"><path d=\"M4 20h4.2L19 9.2 14.8 5 4 15.8V20Z\"/><path d=\"M13.6 6.2 17.8 10.4\"/></svg></button><button class=\"session-agent-sheet-button\" id=\"open-detail-drawer-button\" type=\"button\" aria-label=\"当前会话智能体\" aria-controls=\"mobile-agent-sheet\" aria-expanded=\"false\"><svg viewBox=\"0 0 24 24\" aria-hidden=\"true\"><path d=\"M6 7.5h12v9H6z\"/><path d=\"M9 10.5h.1M15 10.5h.1\"/><path d=\"M10 14h4\"/><path d=\"M12 4.5v3M8 19.5h8\"/></svg></button></div>",
            "<section class=\"worker-session-nav\" id=\"worker-session-nav\" hidden aria-label=\"工作器会话导航\"><div><div class=\"worker-session-nav-kicker\">工作器会话</div><strong id=\"worker-session-nav-title\">Worker</strong></div><button id=\"worker-session-back-button\" type=\"button\">返回主控</button></section>",
            "</div>",
            "<div class=\"session-worker-rail\" id=\"session-worker-rail\" hidden aria-label=\"当前会话 Worker 状态\"></div>",
            "<div class=\"session-tree-dropdown session-tree-inline-panel\" id=\"session-tree-dropdown\" hidden><div class=\"session-tree\" id=\"session-tree\">等待会话真源</div></div>",
            "</section>",
            "</header>",
            "<section class=\"mobile-home-dashboard\" id=\"mobile-home-dashboard\" aria-label=\"会话首页\"><article class=\"mobile-home-card mobile-active-card\"><div class=\"mobile-home-card-head\"><span class=\"settings-status-marker attention\" id=\"mobile-home-active-marker\" aria-hidden=\"true\"></span><span class=\"mobile-home-kicker\">正在运行</span></div><strong id=\"mobile-home-active-title\">暂无运行中会话</strong><p id=\"mobile-home-active-copy\">多个活着的 Agent 和会话会同时显示在这里。</p><div class=\"mobile-home-session-list mobile-running-session-list\" id=\"mobile-home-active-list\">等待活动真源</div></article><article class=\"mobile-home-card mobile-history-card\"><div class=\"mobile-home-card-head\"><span class=\"settings-status-marker ok\" aria-hidden=\"true\"></span><span class=\"mobile-home-kicker\">历史会话</span></div><strong id=\"mobile-home-session-count\">0 个会话</strong><div class=\"mobile-home-session-list mobile-static-session-list\" id=\"mobile-home-session-list\">等待会话真源</div></article></section>",
            "<section class=\"mobile-agent-summary-strip\" id=\"mobile-agent-summary-strip\" aria-label=\"Agent 状态\">",
            "<button class=\"mobile-agent-summary-button\" id=\"open-mobile-agent-sheet-button\" type=\"button\" aria-controls=\"mobile-agent-sheet\" aria-expanded=\"false\">",
            "<span class=\"mobile-agent-summary-dot\" id=\"mobile-agent-summary-dot\" aria-hidden=\"true\"></span>",
            "<span class=\"mobile-agent-summary-content\"><span class=\"mobile-agent-summary-title\" id=\"mobile-agent-summary-title\">Agent 状态不可用</span><span class=\"mobile-agent-summary-copy\" id=\"mobile-agent-summary-copy\">等待任务中心真源</span></span>",
            "<span class=\"mobile-agent-summary-chevron\" aria-hidden=\"true\">⌃</span>",
            "</button>",
            "</section>",
            "<div class=\"mobile-bottom-entries\" aria-label=\"移动端底部快速入口\"><button class=\"mobile-drawer-button mobile-corner-button\" id=\"mobile-new-entry-button\" type=\"button\" aria-label=\"新建会话\"><svg viewBox=\"0 0 24 24\" aria-hidden=\"true\"><path d=\"M5 6h14v9H9l-4 3V6Z\"/><path d=\"M12 8.5v4\"/><path d=\"M10 10.5h4\"/></svg></button><button class=\"mobile-drawer-button mobile-corner-button\" id=\"open-session-drawer-button\" type=\"button\" aria-label=\"搜索会话\" aria-controls=\"session-list\"><svg viewBox=\"0 0 24 24\" aria-hidden=\"true\"><circle cx=\"10.5\" cy=\"10.5\" r=\"5.8\"/><path d=\"m15 15 4.5 4.5\"/></svg></button></div>",
            "<section class=\"conversation-region region-card\">",
            "<div class=\"region-header\">",
            "<div class=\"turn-status\">",
            "<span class=\"status-dot\" id=\"turn-status\">等待中</span>",
            "</div>",
            "</div>",
            "<div class=\"stream-stage\">",
            "<div class=\"message-list autonomous\" id=\"message-list\">",
            "<div class=\"chat-empty-state\"><div class=\"chat-empty-title\">新会话</div><div class=\"chat-empty-copy\">发送消息开始当前会话。</div></div>",
            "</div>",
            "<button class=\"conversation-bottom-button\" id=\"conversation-bottom-button\" type=\"button\" aria-label=\"回到底部\" hidden><span aria-hidden=\"true\">↓</span></button>",
            "</div>",
            "<section class=\"composer-card\">",
            "<form class=\"composer-grid\" id=\"composer-form\">",
            "<textarea class=\"composer-input\" id=\"composer-input\" placeholder=\"输入新的任务或继续当前 turn\"></textarea>",
            "<div class=\"composer-actions\">",
            "<button class=\"button\" id=\"send-button\" type=\"submit\">发送</button>",
            "<button class=\"button secondary\" id=\"cancel-button\" type=\"button\">停止</button>",
            "</div>",
            "</form>",
            "<div class=\"composer-control-strip\" aria-label=\"输入框控制\">",
            "<label class=\"control-chip\" id=\"attach-file-button\" for=\"attachment-file-input\" role=\"button\" tabindex=\"0\">加文件</label>",
            "<label class=\"control-chip\" id=\"attach-image-button\" for=\"attachment-image-input\" role=\"button\" tabindex=\"0\">加图片</label>",
            "<label class=\"control-chip\" id=\"attach-video-button\" for=\"attachment-video-input\" role=\"button\" tabindex=\"0\">加视频</label>",
            "<button class=\"control-chip\" id=\"preview-attachments-button\" type=\"button\">预览附件</button>",
            "<button class=\"control-chip\" id=\"refresh-session-button\" type=\"button\">刷新会话</button>",
            "<label class=\"cwd-control\" for=\"cwd-input\"><span>工作目录</span><input id=\"cwd-input\" type=\"text\" placeholder=\"/path/to/workspace\" autocomplete=\"off\" /></label>",
            "<label class=\"model-control\" for=\"model-selector\"><span>模型</span><select id=\"model-selector\"><option value=\"运行时\">运行时配置</option></select></label>",
            "<input id=\"attachment-file-input\" type=\"file\" multiple hidden />",
            "<input id=\"attachment-image-input\" type=\"file\" accept=\"image/*\" multiple hidden />",
            "<input id=\"attachment-video-input\" type=\"file\" accept=\"video/*\" multiple hidden />",
            "</div>",
            "<div class=\"composer-context-strip\" id=\"composer-context-strip\" aria-label=\"上下文统计\" hidden>",
            "<button class=\"control-chip\" id=\"compact-context-button\" type=\"button\" title=\"清理错误历史后压缩上下文\">压缩上下文</button>",
            "<span class=\"context-stat\" id=\"context-stat-cache-hit\" title=\"本次缓存命中率\">缓存 --</span>",
            "<span class=\"context-stat\" id=\"context-stat-cache-avg\" title=\"平均缓存命中率\">平均 --</span>",
            "<span class=\"context-stat\" id=\"context-stat-thinking\" title=\"思考强度\">思考 --</span>",
            "<span class=\"context-stat\" id=\"context-stat-context\" title=\"当前上下文用量\">上下文 --</span>",
            "<span class=\"context-stat\" id=\"context-stat-compacted\" title=\"本次压缩量\">压缩 --</span>",
            "</div>",
            "<div class=\"attachment-tray\" id=\"attachment-tray\" aria-live=\"polite\"></div>",
            "<div class=\"command-status\" id=\"command-status\">命令空闲</div>",
            "</section>",
            "</section>",
            "</section>",
            "<div class=\"layout-resizer layout-resizer-right\" data-layout-resizer=\"right\" role=\"separator\" aria-orientation=\"vertical\" aria-label=\"调整详情面板宽度\" tabindex=\"0\"></div>",
            "<dialog class=\"new-session-dialog\" id=\"new-session-dialog\" aria-labelledby=\"new-session-dialog-title\">",
            "<form class=\"new-session-panel\" id=\"new-session-form\" method=\"dialog\">",
            "<div class=\"new-session-head\">",
            "<div><div class=\"eyebrow\">新建</div><h2 class=\"new-session-title\" id=\"new-session-dialog-title\">开始工作</h2></div>",
            "<button class=\"dialog-close-button\" id=\"new-session-cancel-button\" type=\"button\">关闭</button>",
            "</div>",
            "<div class=\"new-session-choice\" role=\"radiogroup\" aria-label=\"新建类型\">",
            "<label class=\"new-session-option\"><input type=\"radio\" name=\"new-session-kind\" value=\"conversation\" checked /><span><strong>新建会话</strong><small>全局对话</small></span></label>",
            "<label class=\"new-session-option\"><input type=\"radio\" name=\"new-session-kind\" value=\"task\" /><span><strong>新建任务</strong><small>选择目标目录</small></span></label>",
            "</div>",
            "<label class=\"new-task-path-control\" for=\"new-session-cwd-input\"><span>任务目录</span><div class=\"new-task-path-row\"><input id=\"new-session-cwd-input\" type=\"text\" placeholder=\"选择或输入路径\" autocomplete=\"off\" /><button class=\"control-chip\" id=\"new-session-browse-button\" type=\"button\">选择</button></div></label>",
            "<div class=\"new-task-path-presets\" id=\"new-task-path-presets\" aria-label=\"任务目录选项\">",
            "<button class=\"path-preset-button\" type=\"button\" data-cwd=\"/Volumes/extension/code/freehand\">freehand</button>",
            "<button class=\"path-preset-button\" type=\"button\" data-cwd=\"/Volumes/extension/code\">code</button>",
            "<button class=\"path-preset-button\" type=\"button\" data-cwd=\"/Users/fanzhang/code\">~/code</button>",
            "</div>",
            "<div class=\"new-session-actions\">",
            "<button class=\"session-bulk-button\" id=\"new-session-close-button\" type=\"button\">取消</button>",
            "<button class=\"session-task-button\" id=\"new-session-confirm-button\" type=\"submit\">创建</button>",
            "</div>",
            "</form>",
            "</dialog>",
            "<dialog class=\"timer-dashboard-dialog\" id=\"timer-dashboard-dialog\" aria-labelledby=\"timer-dashboard-title\">",
            "<form class=\"timer-dashboard-panel\" id=\"timer-dashboard-form\" method=\"dialog\">",
            "<div class=\"new-session-head\">",
            "<div><div class=\"eyebrow\">定时</div><h2 class=\"new-session-title\" id=\"timer-dashboard-title\">定时任务面板</h2></div>",
            "<button class=\"dialog-close-button\" id=\"timer-dashboard-close-button\" type=\"button\">关闭</button>",
            "</div>",
            "<p class=\"settings-note\">定时器是独立的运行时真源。到期后可以把持久化的提示词作为新 turn 注入到选中的 主控会话。</p>",
            "<div class=\"timer-form-grid\">",
            "<label><span>模式</span><select id=\"timer-mode-input\"><option value=\"relative\">相对倒计时</option><option value=\"absolute\">绝对 Unix 时间</option><option value=\"recurring\">循环 / cron</option></select></label>",
            "<label><span>延迟秒数</span><input id=\"timer-delay-input\" type=\"number\" min=\"1\" step=\"1\" value=\"180\" /></label>",
            "<label><span>触发 Unix 秒</span><input id=\"timer-run-at-input\" type=\"number\" min=\"0\" step=\"1\" /></label>",
            "<label><span>重复类型</span><select id=\"timer-repeat-kind-input\"><option value=\"interval\">间隔</option><option value=\"daily\">每天本地时间</option><option value=\"weekly\">每周本地时间</option><option value=\"cron\">Cron</option></select></label>",
            "<label><span>间隔秒数</span><input id=\"timer-interval-input\" type=\"number\" min=\"1\" step=\"1\" value=\"300\" /></label>",
            "<label><span>本日秒数</span><input id=\"timer-time-of-day-input\" type=\"number\" min=\"0\" max=\"86399\" step=\"1\" value=\"32400\" /></label>",
            "<label><span>星期 0..6</span><input id=\"timer-weekdays-input\" type=\"text\" value=\"1,2,3,4,5\" autocomplete=\"off\" /></label>",
            "<label><span>Cron 表达式</span><input id=\"timer-cron-input\" type=\"text\" value=\"*/15 9-17 * * 1-5\" autocomplete=\"off\" /></label>",
            "<label><span>最大执行次数</span><input id=\"timer-max-runs-input\" type=\"number\" min=\"1\" step=\"1\" value=\"1\" /></label>",
            "<label><span>来源会话</span><select id=\"timer-source-session-input\"><option value=\"\">内部唤醒</option></select></label>",
            "</div>",
            "<label class=\"timer-text-control\"><span>原因</span><input id=\"timer-reason-input\" type=\"text\" value=\"重新检查当前工作\" autocomplete=\"off\" /></label>",
            "<label class=\"timer-text-control\"><span>唤醒提示词</span><textarea id=\"timer-prompt-input\">检查当前框架真源，然后决定 Master 下一步动作。</textarea></label>",
            "<div class=\"new-session-actions\">",
            "<button class=\"session-bulk-button\" id=\"timer-dashboard-refresh-button\" type=\"button\">刷新定时器</button>",
            "<button class=\"session-task-button\" id=\"timer-dashboard-create-button\" type=\"submit\">创建定时器</button>",
            "</div>",
            "<div class=\"settings-note\" id=\"timer-dashboard-status\">等待定时器投影</div>",
            "<div class=\"timer-dashboard-list\" id=\"timer-dashboard-list\">等待定时器真源</div>",
            "<div class=\"timer-dashboard-history\" id=\"timer-dashboard-history\">等待定时器 ledger</div>",
            "</form>",
            "</dialog>",
            "<dialog class=\"tools-dashboard-dialog\" id=\"tools-dashboard-dialog\" aria-labelledby=\"tools-dashboard-title\">",
            "<form class=\"tools-dashboard-panel\" method=\"dialog\">",
            "<div class=\"new-session-head\">",
            "<div><div class=\"eyebrow\">工具</div><h2 class=\"new-session-title\" id=\"tools-dashboard-title\">内置工具注册表</h2></div>",
            "<button class=\"dialog-close-button\" id=\"tools-dashboard-close-button\" type=\"button\">关闭</button>",
            "</div>",
            "<p class=\"settings-note\">工具来自权威真源注册表投影。这里只展示 schema、暴露范围、权限和示例；会话中的工具 turn 在各自对话里渲染。</p>",
            "<div class=\"new-session-actions\">",
            "<button class=\"session-bulk-button\" id=\"tools-dashboard-refresh-button\" type=\"button\">刷新工具</button>",
            "</div>",
            "<div class=\"settings-note\" id=\"tools-dashboard-status\">等待工具注册表投影</div>",
            "<div class=\"tools-dashboard-guidance\" id=\"tools-dashboard-guidance\">等待注册表引导</div>",
            "<div class=\"tools-dashboard-list\" id=\"tools-dashboard-list\">等待工具注册表真源</div>",
            "</form>",
            "</dialog>",
            "<dialog class=\"session-search-dialog\" id=\"session-search-dialog\" aria-labelledby=\"session-search-title\">",
            "<form class=\"session-search-panel\" id=\"session-search-form\" method=\"dialog\">",
            "<div class=\"new-session-head\">",
            "<div><div class=\"eyebrow\">搜索</div><h2 class=\"new-session-title\" id=\"session-search-title\">持久化会话搜索</h2></div>",
            "<button class=\"dialog-close-button\" id=\"session-search-close-button\" type=\"button\">关闭</button>",
            "</div>",
            "<p class=\"settings-note\">搜索读取 权威真源的持久化会话索引。Worker 命中会缩进到父 主控会话下，不会作为一级会话出现。</p>",
            "<div class=\"session-search-control\"><label><span>查询</span><input id=\"session-search-input\" type=\"search\" autocomplete=\"off\" placeholder=\"搜索会话标题、cwd、摘要或子 Worker 结果\" /></label><button class=\"session-task-button\" id=\"session-search-submit-button\" type=\"submit\">搜索</button></div>",
            "<div class=\"settings-note\" id=\"session-search-status\">输入关键词搜索持久化会话。</div>",
            "<div class=\"session-search-results\" id=\"session-search-results\">尚未查询。</div>",
            "</form>",
            "</dialog>",
            "<aside class=\"inspector\">",
            "<div class=\"drawer-panel-head\">",
            "<div><div class=\"eyebrow\" id=\"inspector-eyebrow\">生命周期观察</div><h2 class=\"inspector-title\" id=\"inspector-title\">任务与智能体生命周期</h2></div>",
            "<button class=\"drawer-close-button\" id=\"close-detail-drawer-button\" type=\"button\" aria-label=\"关闭详情\">关闭</button>",
            "</div>",
            "<p class=\"page-copy\" id=\"inspector-copy\">观察 Master/工作器生命周期、当前执行、事件和必要的调试摘要；活跃 Worker 会高亮并可点击查看对应任务进度。</p>",
            "<div class=\"stack inspector-debug-panel\" id=\"inspector-debug-panel\">",
            "<section class=\"inspector-block\">",
            "<div class=\"meta-label\">调试状态</div>",
            "<div class=\"inspector-block-title\" id=\"debug-status\">等待中</div>",
            "<div class=\"inspector-copy\" id=\"debug-lines\">-</div>",
            "</section>",
            "<section class=\"inspector-block checkpoint-block\">",
            "<div class=\"meta-label\">检查点</div>",
            "<div class=\"inspector-block-title\" id=\"checkpoint-status\">等待中</div>",
            "<div class=\"checkpoint-list\" id=\"checkpoint-list\">-</div>",
            "</section>",
            "<section class=\"inspector-block phase2-board-block\">",
            "<div class=\"meta-label\">任务面板</div>",
            "<div class=\"inspector-block-title\" id=\"task-board-status\">等待中</div>",
            "<div class=\"phase2-list\" id=\"task-board-list\">-</div>",
            "</section>",
            "<section class=\"inspector-block phase2-board-block\">",
            "<div class=\"meta-label\">智能体面板</div>",
            "<div class=\"inspector-block-title\" id=\"agent-board-status\">等待中</div>",
            "<div class=\"phase2-list\" id=\"agent-board-list\">-</div>",
            "</section>",
            "<section class=\"inspector-block phase2-board-block\">",
            "<div class=\"meta-label\">事件收件箱</div>",
            "<div class=\"inspector-block-title\" id=\"event-inbox-status\">等待中</div>",
            "<div class=\"phase2-list\" id=\"event-inbox-list\">-</div>",
            "</section>",
            "<section class=\"inspector-block phase2-board-block\">",
            "<div class=\"meta-label\">执行历史</div>",
            "<div class=\"inspector-block-title\" id=\"task-history-status\">等待中</div>",
            "<div class=\"phase2-list\" id=\"task-history-list\">-</div>",
            "</section>",
            "<section class=\"inspector-block phase2-board-block\">",
            "<div class=\"meta-label\">工作器控制</div>",
            "<div class=\"inspector-block-title\" id=\"worker-control-status\">等待中</div>",
            "<div class=\"phase2-list\" id=\"worker-control-list\">-</div>",
            "</section>",
            "</div>",
            "<div class=\"settings-shell\" id=\"settings-shell\" hidden>",
            "<div class=\"settings-grid\">",
            "<section class=\"settings-panel\" data-settings-page=\"root\" aria-label=\"设置一级入口\"><section class=\"settings-nav-grid\"><button class=\"settings-nav-card\" type=\"button\" data-settings-section=\"models\" data-settings-target=\"models\" data-settings-state=\"partial\"><span class=\"settings-status-marker partial\" aria-hidden=\"true\"></span><div><strong>模型</strong><small>模型服务、模型组、路由和能力测试</small></div><span class=\"settings-nav-chevron\" aria-hidden=\"true\">›</span></button><button class=\"settings-nav-card\" type=\"button\" data-settings-section=\"agent-runtime\" data-settings-target=\"agent-runtime\" data-settings-state=\"partial\"><span class=\"settings-status-marker partial\" aria-hidden=\"true\"></span><div><strong>智能体运行时</strong><small>工作器上限、能力、Skill、记忆和集成</small></div><span class=\"settings-nav-chevron\" aria-hidden=\"true\">›</span></button><button class=\"settings-nav-card\" type=\"button\" data-settings-section=\"connectivity\" data-settings-target=\"connectivity\" data-settings-state=\"partial\"><span class=\"settings-status-marker partial\" aria-hidden=\"true\"></span><div><strong>连接</strong><small>daemon 路由、Tailscale、Relay、二维码和 Android 壳</small></div><span class=\"settings-nav-chevron\" aria-hidden=\"true\">›</span></button><button class=\"settings-nav-card\" type=\"button\" data-settings-section=\"observability\" data-settings-target=\"observability\" data-settings-state=\"partial\"><span class=\"settings-status-marker partial\" aria-hidden=\"true\"></span><div><strong>可观测性</strong><small>诊断、生命周期证据和导出包</small></div><span class=\"settings-nav-chevron\" aria-hidden=\"true\">›</span></button><button class=\"settings-nav-card\" type=\"button\" data-settings-section=\"appearance\" data-settings-target=\"appearance\" data-settings-state=\"partial\"><span class=\"settings-status-marker partial\" aria-hidden=\"true\"></span><div><strong>外观</strong><small>主题已存在；字体和密度设置仍待完成</small></div><span class=\"settings-nav-chevron\" aria-hidden=\"true\">›</span></button><button class=\"settings-nav-card\" type=\"button\" data-settings-section=\"about\" data-settings-target=\"about\" data-settings-state=\"attention\"><span class=\"settings-status-marker attention\" aria-hidden=\"true\"></span><div><strong>关于</strong><small>版本、隐私和反馈页未实现</small></div><span class=\"settings-nav-chevron\" aria-hidden=\"true\">›</span></button></section>",
            "<p class=\"settings-status-legend\"><span><i class=\"settings-status-marker ok\" aria-hidden=\"true\"></i>已接权威真源</span><span><i class=\"settings-status-marker partial\" aria-hidden=\"true\"></i>部分完成</span><span><i class=\"settings-status-marker attention\" aria-hidden=\"true\"></i>占位/未实现</span></p></section>",
            "<section class=\"settings-panel\" data-settings-page=\"models\" data-settings-group=\"models\" hidden><header class=\"settings-page-header\"><button class=\"settings-back-button\" type=\"button\" data-settings-target=\"root\">返回</button><div><small>设置</small><strong>模型</strong></div><span id=\"settings-provider-summary\">加载中</span></header><section class=\"settings-nav-grid settings-second-level\"><button class=\"settings-nav-card\" type=\"button\" data-settings-target=\"models.provider-config\" data-settings-state=\"ok\"><span class=\"settings-status-marker ok\" aria-hidden=\"true\"></span><div><strong>模型服务配置</strong><small>注册表、端点、鉴权来源、协议、模型和能力测试</small></div><span class=\"settings-nav-chevron\" aria-hidden=\"true\">›</span></button><button class=\"settings-nav-card\" type=\"button\" data-settings-target=\"models.strategy\" data-settings-state=\"ok\"><span class=\"settings-status-marker ok\" aria-hidden=\"true\"></span><div><strong>模型服务切换与策略</strong><small>主模型服务和备用模型服务选择</small></div><span class=\"settings-nav-chevron\" aria-hidden=\"true\">›</span></button><button class=\"settings-nav-card\" type=\"button\" data-settings-target=\"models.model-groups\" data-settings-state=\"ok\"><span class=\"settings-status-marker ok\" aria-hidden=\"true\"></span><div><strong>模型组</strong><small>主模型、子模型、搜索、标题、备用和负载均衡路由</small></div><span class=\"settings-nav-chevron\" aria-hidden=\"true\">›</span></button><article class=\"settings-nav-card is-static\" data-settings-state=\"partial\"><span class=\"settings-status-marker partial\" aria-hidden=\"true\"></span><div><strong>模型服务模板</strong><small>OpenAI 和 Anthropic 可用；更多模板部分完成</small></div></article><article class=\"settings-nav-card is-static\" data-settings-state=\"attention\"><span class=\"settings-status-marker attention\" aria-hidden=\"true\"></span><div><strong>令牌用量</strong><small>模型服务和会话用量页面未实现</small></div></article></section></section>",
            "<section class=\"settings-panel settings-detail-page settings-provider-config-page\" id=\"settings-provider-config-page\" data-settings-page=\"models.provider-config\" data-settings-group=\"models\" hidden><header class=\"settings-page-header\"><button class=\"settings-back-button\" type=\"button\" data-settings-target=\"models\">返回</button><div><small>设置 / 模型</small><strong>模型服务配置</strong></div><span class=\"settings-status-marker ok\" aria-label=\"已接权威真源\"></span></header>",
            "<div class=\"settings-row\"><span>当前模型服务</span><strong id=\"settings-provider-id\">加载中</strong></div><div class=\"settings-row\"><span>类型</span><strong id=\"settings-provider-type\">加载中</strong></div><div class=\"settings-row\"><span>协议</span><strong id=\"settings-provider-protocol\">加载中</strong></div><div class=\"settings-row\"><span>主机</span><strong id=\"settings-provider-host\">加载中</strong></div><div class=\"settings-row\"><span>模型选择器</span><strong id=\"settings-model-value\">运行时配置</strong></div><div class=\"settings-row\"><span>联网搜索</span><strong id=\"settings-provider-web-search\">加载中</strong></div><div class=\"settings-row\"><span>鉴权来源</span><strong id=\"settings-provider-auth\">加载中</strong></div><div class=\"settings-row\"><span>生效方式</span><strong id=\"settings-restart-required\">加载中</strong></div><div class=\"settings-row\"><span>配置状态</span><strong id=\"settings-config-error\">无</strong></div>",
            "<div class=\"settings-provider-registry\" id=\"settings-provider-registry-list\">加载模型服务注册表</div>",
            "<form class=\"settings-provider-form\" id=\"settings-provider-form\"><label><span>模型服务 ID</span><input id=\"settings-provider-id-input\" name=\"provider_id\" autocomplete=\"off\" /></label><label><span>类型</span><select id=\"settings-provider-type-input\" name=\"provider_type\"><option value=\"openai\">OpenAI 兼容</option><option value=\"anthropic\">Anthropic Messages</option></select></label><label><span>协议</span><select id=\"settings-provider-protocol-input\" name=\"provider_protocol\"><option value=\"responses\">Responses</option><option value=\"chat_completions\">Chat Completions</option><option value=\"messages\">Messages</option></select></label><label><span>端点</span><input id=\"settings-provider-url-input\" name=\"base_url\" placeholder=\"https://api.example.com/v1\" autocomplete=\"off\" /></label><label><span>默认模型</span><input id=\"settings-provider-model-input\" name=\"default_model\" autocomplete=\"off\" /></label><label><span>联网搜索</span><select id=\"settings-provider-web-search-input\" name=\"web_search\"><option value=\"auto\">自动</option><option value=\"disabled\">关闭</option></select></label><label><span>凭证环境变量</span><input id=\"settings-provider-env-input\" name=\"api_key_env\" placeholder=\"PROVIDER_CREDENTIAL\" autocomplete=\"off\" /></label><div class=\"settings-note\" id=\"settings-provider-save-status\">新增或更新一个使用环境变量鉴权的模型服务。模型服务切换在独立页面。</div><div class=\"settings-note\" id=\"settings-provider-web-search-test-status\">模型服务联网搜索测试尚未运行。</div><button class=\"settings-primary-action\" id=\"settings-provider-save-button\" type=\"submit\">新增/更新模型服务</button><button class=\"settings-secondary-action\" id=\"settings-provider-web-search-test-button\" type=\"button\">测试联网搜索</button></form></section>",
            "<section class=\"settings-panel settings-detail-page settings-provider-strategy-page\" id=\"settings-provider-strategy-page\" data-settings-page=\"models.strategy\" data-settings-group=\"models\" hidden><header class=\"settings-page-header\"><button class=\"settings-back-button\" type=\"button\" data-settings-target=\"models\">返回</button><div><small>设置 / 模型</small><strong>模型服务切换与策略</strong></div><span class=\"settings-status-marker ok\" aria-label=\"已接权威真源\"></span></header><div class=\"settings-provider-switch\" id=\"settings-provider-switch\"><label><span>主模型服务</span><select id=\"settings-provider-current-select\"></select></label><label><span>备用模型服务</span><select id=\"settings-provider-fallback-select\"></select></label><button class=\"settings-primary-action\" id=\"settings-provider-switch-button\" type=\"button\">切换模型服务</button><div class=\"settings-note\" id=\"settings-provider-switch-status\">切换会保存选中的 Agent 模型服务；重启后活动运行时才会生效。</div></div></section>",
            "<section class=\"settings-panel settings-detail-page settings-model-groups-page\" id=\"settings-model-groups-page\" data-settings-page=\"models.model-groups\" data-settings-group=\"models\" hidden><header class=\"settings-page-header\"><button class=\"settings-back-button\" type=\"button\" data-settings-target=\"models\">返回</button><div><small>设置 / 模型</small><strong>模型组</strong></div><span class=\"settings-status-marker ok\" aria-label=\"已接权威真源\"></span></header><div class=\"settings-row\"><span>当前模型组</span><strong id=\"settings-model-group-summary\">加载中</strong></div><div class=\"settings-model-group-switch\" id=\"settings-model-group-switch\"><label><span>启用模型组</span><select id=\"settings-model-group-current-select\"></select></label><button class=\"settings-primary-action\" id=\"settings-model-group-switch-button\" type=\"button\">切换模型组</button><div class=\"settings-note\" id=\"settings-model-group-switch-status\">模型组会改变 Agent 的主模型/备用模型路由；重启后活动运行时才会生效。</div></div><div class=\"settings-model-group-registry\" id=\"settings-model-group-registry-list\">加载模型组</div><form class=\"settings-model-group-form\" id=\"settings-model-group-form\"><label><span>模型组 ID</span><input id=\"settings-model-group-id-input\" name=\"group_id\" autocomplete=\"off\" /></label><label><span>名称</span><input id=\"settings-model-group-label-input\" name=\"label\" autocomplete=\"off\" /></label><label class=\"settings-inline-check\"><input id=\"settings-model-group-enabled-input\" name=\"enabled\" type=\"checkbox\" checked /><span>启用</span></label><label><span>主模型服务</span><select id=\"settings-model-group-primary-provider-input\"></select></label><label><span>主模型</span><input id=\"settings-model-group-primary-model-input\" autocomplete=\"off\" /></label><label><span>子任务模型服务</span><select id=\"settings-model-group-sub-provider-input\"></select></label><label><span>子任务模型</span><input id=\"settings-model-group-sub-model-input\" autocomplete=\"off\" /></label><label><span>搜索模型服务</span><select id=\"settings-model-group-search-provider-input\"></select></label><label><span>搜索模型</span><input id=\"settings-model-group-search-model-input\" autocomplete=\"off\" /></label><label><span>标题模型服务</span><select id=\"settings-model-group-title-provider-input\"></select></label><label><span>标题模型</span><input id=\"settings-model-group-title-model-input\" autocomplete=\"off\" /></label><label><span>备用模型服务</span><select id=\"settings-model-group-fallback-provider-input\"></select></label><label><span>备用模型</span><input id=\"settings-model-group-fallback-model-input\" autocomplete=\"off\" /></label><label><span>负载均衡</span><input id=\"settings-model-group-load-balance-input\" placeholder=\"provider:model:weight, provider:model:weight\" autocomplete=\"off\" /></label><label><span>上下文窗口（tokens）</span><input id=\"settings-model-group-context-window-input\" type=\"number\" min=\"1\" step=\"1\" value=\"128000\" /></label><label><span>自动压缩门限（tokens）</span><input id=\"settings-model-group-compaction-threshold-input\" type=\"number\" min=\"1\" step=\"1\" value=\"100000\" /></label><div class=\"settings-note\" id=\"settings-model-group-save-status\">压缩门限必须小于上下文窗口。</div><button class=\"settings-primary-action\" id=\"settings-model-group-save-button\" type=\"submit\">新增/更新模型组</button></form></section>",
            "<section class=\"settings-panel settings-detail-page\" data-settings-page=\"agent-runtime\" data-settings-group=\"agent-runtime\" hidden><header class=\"settings-page-header\"><button class=\"settings-back-button\" type=\"button\" data-settings-target=\"root\">返回</button><div><small>设置</small><strong>智能体运行时</strong></div><span id=\"settings-agent-resource-summary\">加载中</span></header><section class=\"settings-section-card\"><div class=\"settings-subpage-head\"><span class=\"settings-status-marker ok\" aria-hidden=\"true\"></span><div><strong>工作器上限</strong><small>配置真源拥有的工作器容量，运行时重启后生效</small></div></div><div class=\"settings-row\"><span>模型服务模式</span><strong id=\"settings-agent-resource-provider\">加载中</strong></div><div class=\"settings-agent-resource-control\"><button id=\"settings-agent-resource-decrement\" type=\"button\" aria-label=\"降低工作器上限\">−</button><strong id=\"settings-agent-resource-count\">1</strong><span>上限 <span id=\"settings-agent-resource-limit\">5</span></span><button id=\"settings-agent-resource-increment\" type=\"button\" aria-label=\"提高工作器上限\">+</button></div><div class=\"settings-note\" id=\"settings-agent-resource-status\">配置真源从当前 Master 加载。</div><button class=\"settings-primary-action\" id=\"settings-agent-resource-save\" type=\"button\">保存工作器上限</button></section><section class=\"settings-placeholder-list\"><article><span class=\"settings-status-marker partial\" aria-hidden=\"true\"></span><div><strong>工作器能力</strong><small>注册表投影已存在；配置页部分完成</small></div></article><article><span class=\"settings-status-marker attention\" aria-hidden=\"true\"></span><div><strong>Skill、记忆和集成</strong><small>管理页未实现</small></div></article></section></section>",
            "<section class=\"settings-panel settings-detail-page\" data-settings-page=\"connectivity\" data-settings-group=\"connectivity\" hidden><header class=\"settings-page-header\"><button class=\"settings-back-button\" type=\"button\" data-settings-target=\"root\">返回</button><div><small>设置</small><strong>连接</strong></div><span class=\"settings-status-marker partial\" aria-label=\"部分完成\"></span></header><section class=\"settings-section-card\"><div class=\"settings-subpage-head\"><span class=\"settings-status-marker ok\" aria-hidden=\"true\"></span><div><strong>Relay 登录</strong><small id=\"settings-relay-login-summary\">未登录</small></div></div><form class=\"settings-relay-login-form\" id=\"settings-relay-login-form\"><label><span>Relay 根地址</span><input id=\"settings-relay-base-url-input\" name=\"relay_base_url\" placeholder=\"http://100.77.11.8:18443\" autocomplete=\"off\" /></label><label><span>用户名</span><input id=\"settings-relay-username-input\" name=\"relay_username\" autocomplete=\"username\" /></label><label><span>密码</span><input id=\"settings-relay-password-input\" name=\"relay_password\" type=\"password\" autocomplete=\"current-password\" /></label><div class=\"settings-note\" id=\"settings-relay-login-status\">登录后只查询同账号 Agent 目录；密码只用于本次请求，不写入配置。</div><button class=\"settings-primary-action\" id=\"settings-relay-login-button\" type=\"submit\">登录 Relay</button><button class=\"settings-secondary-action\" id=\"settings-relay-refresh-button\" type=\"button\">刷新 Agent 目录</button><button class=\"settings-secondary-action\" id=\"settings-relay-logout-button\" type=\"button\">退出登录</button></form><div class=\"settings-row\"><span>当前账号</span><strong id=\"settings-relay-account\">未登录</strong></div><div class=\"phase2-list\" id=\"settings-relay-agent-list\">等待登录后显示 Agent 目录</div></section><section class=\"settings-section-card\" id=\"settings-account-config-sync\"><div class=\"settings-subpage-head\"><span class=\"settings-status-marker partial\" id=\"settings-account-config-sync-marker\" aria-hidden=\"true\"></span><div><strong>账号配置同步</strong><small id=\"settings-account-config-sync-summary\">未配置</small></div></div><div class=\"settings-row\"><span>账号</span><strong id=\"settings-account-config-sync-account\">未配置</strong></div><div class=\"settings-row\"><span>版本</span><strong id=\"settings-account-config-sync-revision\">未同步</strong></div><div class=\"settings-row\"><span>内容</span><strong id=\"settings-account-config-sync-content\">未同步</strong></div><div class=\"settings-note\" id=\"settings-account-config-sync-status\">登录后可显式拉取并应用同账号配置；首次上传必须由你明确触发。</div><div class=\"settings-inline-actions\"><button class=\"settings-primary-action\" id=\"settings-account-config-pull-button\" type=\"button\">拉取并应用账号配置</button><button class=\"settings-secondary-action\" id=\"settings-account-config-push-button\" type=\"button\">上传本机非 Secret 配置</button></div></section><section class=\"settings-section-card\"><div class=\"settings-subpage-head\"><span class=\"settings-status-marker partial\" aria-hidden=\"true\"></span><div><strong>安卓 APK 升级</strong><small id=\"settings-apk-update-summary\">仅安卓 App</small></div></div><div class=\"settings-row\"><span>升级来源</span><strong id=\"settings-apk-update-source\">守护进程 /android/update.json</strong></div><div class=\"settings-note\" id=\"settings-apk-update-status\">在安卓 App 内打开本设置页可检查并下载新版 APK。</div><button class=\"settings-primary-action\" id=\"settings-apk-update-check-button\" type=\"button\">检查 APK 升级</button></section><section class=\"settings-placeholder-list\"><article><span class=\"settings-status-marker partial\" aria-hidden=\"true\"></span><div><strong>守护进程连接</strong><small>本地和远程注册表已存在；管理页部分完成</small></div></article><article><span class=\"settings-status-marker partial\" aria-hidden=\"true\"></span><div><strong>Tailscale / 二维码</strong><small>路由和引导基础已存在；管理页部分完成</small></div></article></section></section>",
            "<section class=\"settings-panel settings-detail-page settings-diagnostics-page\" data-settings-page=\"observability\" data-settings-group=\"observability\" hidden><header class=\"settings-page-header\"><button class=\"settings-back-button\" type=\"button\" data-settings-target=\"root\">返回</button><div><small>设置</small><strong>可观测性</strong></div><span id=\"settings-diagnostics-summary\">加载中</span></header><section class=\"settings-section-card\"><div class=\"settings-subpage-head\"><span class=\"settings-status-marker ok\" aria-hidden=\"true\"></span><div><strong>诊断日志</strong><small>服务拥有的元数据和脱敏尾部日志</small></div></div><div class=\"settings-row\"><span>运行时目录</span><strong id=\"settings-diagnostics-runtime-home\">加载中</strong></div><div class=\"settings-note\" id=\"settings-diagnostics-status\">诊断只显示服务拥有的日志元数据和脱敏尾部内容。</div><button class=\"settings-primary-action\" id=\"settings-diagnostics-refresh-button\" type=\"button\">刷新诊断</button><div class=\"phase2-list\" id=\"settings-diagnostics-list\">等待诊断投影</div></section><section class=\"settings-placeholder-list\"><article><span class=\"settings-status-marker ok\" aria-hidden=\"true\"></span><div><strong>会话 / 工作器生命周期</strong><small>任务、Agent 和 turn 状态可由权威真源观察</small></div></article><article><span class=\"settings-status-marker attention\" aria-hidden=\"true\"></span><div><strong>导出包</strong><small>诊断导出未实现</small></div></article></section></section>",
            "<section class=\"settings-panel settings-detail-page\" data-settings-page=\"appearance\" data-settings-group=\"appearance\" hidden><header class=\"settings-page-header\"><button class=\"settings-back-button\" type=\"button\" data-settings-target=\"root\">返回</button><div><small>设置</small><strong>外观</strong></div><span class=\"settings-status-marker partial\" aria-label=\"部分完成\"></span></header><section class=\"settings-placeholder-list\"><article><span class=\"settings-status-marker partial\" aria-hidden=\"true\"></span><div><strong>主题</strong><small>浅色和深色切换已在本页外提供</small></div></article><article><span class=\"settings-status-marker attention\" aria-hidden=\"true\"></span><div><strong>字体 / 密度</strong><small>显示控制未实现</small></div></article></section></section>",
            "<section class=\"settings-panel settings-detail-page\" data-settings-page=\"about\" data-settings-group=\"about\" hidden><header class=\"settings-page-header\"><button class=\"settings-back-button\" type=\"button\" data-settings-target=\"root\">返回</button><div><small>设置</small><strong>关于</strong></div><span class=\"settings-status-marker attention\" aria-label=\"占位\"></span></header><section class=\"settings-placeholder-list\"><article><span class=\"settings-status-marker attention\" aria-hidden=\"true\"></span><div><strong>关于 Freehand</strong><small>版本、隐私和反馈页未实现</small></div></article></section></section>",
            "</div>",
            "</div>",
            "</aside>",
            "<section class=\"mobile-agent-sheet\" id=\"mobile-agent-sheet\" role=\"dialog\" aria-modal=\"true\" aria-hidden=\"true\" aria-labelledby=\"mobile-agent-sheet-title\">",
            "<div class=\"mobile-agent-sheet-handle\" aria-hidden=\"true\"></div>",
            "<header class=\"mobile-agent-sheet-header\"><div><div class=\"eyebrow\">当前会话</div><h2 class=\"mobile-agent-sheet-title\" id=\"mobile-agent-sheet-title\">智能体列表</h2></div><button class=\"drawer-close-button\" id=\"close-mobile-agent-sheet-button\" type=\"button\" aria-label=\"关闭 智能体列表\">关闭</button></header>",
            "<div class=\"mobile-agent-sheet-scroll\">",
            "<section class=\"mobile-agent-section\"><div class=\"mobile-agent-section-head\"><div><div class=\"mobile-agent-card-kicker\">Agent 与 Worker</div><h3>选择 Agent 或当前会话的 Worker 任务</h3></div><span id=\"mobile-agent-task-status\">等待中</span></div><div class=\"mobile-agent-list\" id=\"mobile-agent-task-list\"></div></section>",
            "</div>",
            "</section>",
            "</main>",
            "<script type=\"module\" src=\"assets/webui.js?v=__WEBUI_ASSET_VERSION__\"></script>",
            "</body>",
            "</html>"
        ),
        initial_body_attrs, initial_shell_attrs
    ))
}

fn initial_layout_body_attrs(client: Option<&str>) -> &'static str {
    match client {
        Some(ANDROID_WEBVIEW_CLIENT) => ANDROID_WEBVIEW_INITIAL_LAYOUT_ATTRS,
        _ => "",
    }
}

fn initial_layout_shell_attrs(client: Option<&str>) -> &'static str {
    match client {
        Some(ANDROID_WEBVIEW_CLIENT) => ANDROID_WEBVIEW_INITIAL_LAYOUT_ATTRS,
        _ => "",
    }
}
