pub const ANDROID_WEBVIEW_CLIENT: &str = "android-webview";
const ANDROID_WEBVIEW_INITIAL_LAYOUT_ATTRS: &str =
    " data-layout-client=\"android-webview\" data-layout-shape=\"tablet_portrait\"";

pub fn render_webui_smoke() -> String {
    render_webui_smoke_for_client(None)
}

pub fn render_webui_smoke_for_client(client: Option<&str>) -> String {
    let initial_body_attrs = initial_layout_body_attrs(client);
    let initial_shell_attrs = initial_layout_shell_attrs(client);
    format!(
        concat!(
            "<!DOCTYPE html>",
            "<html lang=\"zh-CN\">",
            "<head>",
            "<meta charset=\"UTF-8\" />",
            "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, viewport-fit=cover\" />",
            "<title>Freehand WebUI</title>",
            "<link rel=\"stylesheet\" href=\"/assets/theme.css?v=20260724-model-groups-ui\" />",
            "<link rel=\"stylesheet\" href=\"/assets/webui.css?v=20260724-model-groups-ui\" />",
            "</head>",
            "<body class=\"theme-light\"{}>",
            "<main class=\"app-shell\" data-webui-shell=\"true\"{} ",
            "data-adp-endpoint=\"/adp\" ",
            "data-turn-query=\"/ui/query/latest-active-turn\" ",
            "data-turn-subscribe=\"/ui/subscribe/turn/latest\" ",
            "data-debug-query-base=\"/ui/query/debug/\" ",
            "data-debug-subscribe-base=\"/ui/subscribe/debug/\" ",
            "data-checkpoint-query=\"/ui/query/checkpoints\" ",
            "data-command-endpoint=\"/ui/command\" ",
            "data-selected-session=\"\" ",
            "data-selected-turn=\"\">",
            "<div class=\"mobile-drawer-scrim\" id=\"mobile-drawer-scrim\" aria-hidden=\"true\"></div>",
            "<aside class=\"rail\">",
            "<div class=\"brand\"><img class=\"brand-logo\" src=\"/assets/logo.png?v=20260723-logo-refresh\" alt=\"Freehand\" /></div>",
            "<div class=\"rail-group\">",
            "<button class=\"rail-button active\" type=\"button\">WS</button>",
            "<button class=\"rail-button\" type=\"button\">ND</button>",
            "<button class=\"rail-button\" type=\"button\">RP</button>",
            "<button class=\"rail-button\" type=\"button\">DG</button>",
            "</div>",
            "</aside>",
            "<aside class=\"sidebar\">",
            "<div class=\"drawer-panel-head\">",
            "<div><div class=\"eyebrow\">sessions</div><h1 class=\"page-title\">Sessions</h1></div>",
            "<button class=\"drawer-close-button\" id=\"close-session-drawer-button\" type=\"button\" aria-label=\"Close sessions\">Close</button>",
            "</div>",
            "<label class=\"task-cwd-control\" for=\"task-cwd-input\"><span>Task target directory</span><input id=\"task-cwd-input\" type=\"text\" placeholder=\"/Volumes/extension/code/freehand\" autocomplete=\"off\" /></label>",
            "<div class=\"session-create-actions\">",
            "<button class=\"session-conversation-button\" id=\"new-conversation-button\" type=\"button\">New conversation</button>",
            "<button class=\"session-task-button\" id=\"new-task-button\" type=\"button\">New task</button>",
            "</div>",
            "<div class=\"session-bulk-toolbar\" aria-label=\"Session management\">",
            "<div class=\"session-bulk-summary\"><span class=\"session-bulk-label\">bulk</span><span class=\"session-bulk-count\" id=\"session-bulk-count\">0 selected</span></div>",
            "<div class=\"session-bulk-actions\">",
            "<button class=\"session-bulk-button select-all\" id=\"session-select-all-button\" type=\"button\">Select all</button>",
            "<button class=\"session-bulk-button\" id=\"session-clear-selection-button\" type=\"button\">Clear</button>",
            "<button class=\"session-bulk-button\" id=\"session-rename-selected-button\" type=\"button\" disabled>Rename</button>",
            "<button class=\"session-bulk-button danger\" id=\"session-delete-selected-button\" type=\"button\" disabled>Remove</button>",
            "</div>",
            "</div>",
            "<div class=\"session-list\" id=\"session-list\">",
            "<section class=\"session-item active\"><div class=\"meta-label\">loading</div><div class=\"session-title\" id=\"session-title\">waiting for service state</div><div class=\"session-copy\" id=\"session-copy\">no active turn yet</div></section>",
            "</div>",
            "</aside>",
            "<div class=\"layout-resizer layout-resizer-left\" data-layout-resizer=\"left\" role=\"separator\" aria-orientation=\"vertical\" aria-label=\"Resize sessions panel\" tabindex=\"0\"></div>",
            "<section class=\"workspace\">",
            "<header class=\"topbar region-card\">",
            "<div class=\"topbar-main\">",
            "<div class=\"mobile-shell-controls\" aria-label=\"Mobile quick entrances\">",
            "<button class=\"mobile-drawer-button mobile-corner-button mobile-config-entry\" id=\"open-settings-drawer-button\" type=\"button\" aria-label=\"配置\" aria-controls=\"settings-shell\"><svg viewBox=\"0 0 24 24\" aria-hidden=\"true\"><path d=\"M12 8.2a3.8 3.8 0 1 0 0 7.6 3.8 3.8 0 0 0 0-7.6Z\"/><path d=\"M20.4 13.4v-2.8l-2.2-.5a7 7 0 0 0-.7-1.6l1.2-1.9-2-2-1.9 1.2a7 7 0 0 0-1.6-.7L12.8 3h-2.8l-.5 2.2a7 7 0 0 0-1.6.7L6 4.7l-2 2 1.2 1.9a7 7 0 0 0-.7 1.6l-2.2.5v2.8l2.2.5c.2.6.4 1.1.7 1.6L4 17.4l2 2 1.9-1.2c.5.3 1 .5 1.6.7l.5 2.2h2.8l.5-2.2c.6-.2 1.1-.4 1.6-.7l1.9 1.2 2-2-1.2-1.9c.3-.5.5-1 .7-1.6l2.1-.5Z\"/></svg></button>",
            "<div class=\"mobile-top-right-entries\"><button class=\"mobile-drawer-button mobile-corner-button\" id=\"open-timer-dashboard-button\" type=\"button\" aria-label=\"定时任务\"><svg viewBox=\"0 0 24 24\" aria-hidden=\"true\"><circle cx=\"12\" cy=\"12\" r=\"8.5\"/><path d=\"M12 6.8v5.5l3.6 2.2\"/></svg></button><button class=\"mobile-drawer-button mobile-corner-button\" id=\"open-tools-dashboard-button\" type=\"button\" aria-label=\"内置工具\"><svg viewBox=\"0 0 24 24\" aria-hidden=\"true\"><path d=\"M4 6h16v12H4z\"/><path d=\"m8 10 3 2-3 2\"/><path d=\"M13 15h4\"/></svg></button></div>",
            "</div>",
            "<div class=\"topbar-title-wrap\">",
            "<h1 class=\"page-title\">Freehand</h1>",
            "</div>",
            "<div class=\"topbar-actions\">",
            "<button class=\"debug-toggle\" id=\"settings-shell-toggle\" type=\"button\" aria-pressed=\"false\">Settings</button>",
            "<div class=\"theme-toggle\" aria-label=\"Theme switch\">",
            "<button class=\"theme-button is-active\" data-theme=\"light\" type=\"button\">White</button>",
            "<button class=\"theme-button\" data-theme=\"dark\" type=\"button\">Black</button>",
            "</div>",
            "<button class=\"debug-toggle\" id=\"debug-details-toggle\" type=\"button\" aria-pressed=\"false\">Debug details</button>",
            "<span class=\"status-pill ok\" id=\"workspace-status\">booting</span>",
            "</div>",
            "</div>",
            "<section class=\"session-relation-header\" id=\"session-relation-header\" aria-label=\"Master and Worker session tree\">",
            "<div class=\"session-dashbar-row\">",
            "<button class=\"session-dashbar\" id=\"session-relation-toggle-button\" type=\"button\" aria-expanded=\"false\" aria-controls=\"session-tree-dropdown\">",
            "<span class=\"session-dashbar-kicker\" id=\"session-relation-kicker\">Master session</span>",
            "<span class=\"session-dashbar-title\" id=\"session-relation-title\">No session selected</span>",
            "<span class=\"session-dashbar-metrics\" id=\"session-relation-metrics\">0 tasks</span>",
            "<span class=\"session-dashbar-copy\" id=\"session-relation-copy\">Click to open session tree</span>",
            "<span class=\"session-dashbar-chevron\" aria-hidden=\"true\">⌄</span>",
            "</button>",
            "<section class=\"worker-session-nav\" id=\"worker-session-nav\" hidden aria-label=\"Worker session navigation\"><div><div class=\"worker-session-nav-kicker\">Worker conversation</div><strong id=\"worker-session-nav-title\">Worker</strong></div><button id=\"worker-session-back-button\" type=\"button\">Back to Master</button></section>",
            "</div>",
            "<div class=\"session-tree-dropdown\" id=\"session-tree-dropdown\" hidden><div class=\"session-tree\" id=\"session-tree\">Waiting for session truth</div></div>",
            "</section>",
            "</header>",
            "<section class=\"mobile-home-dashboard\" id=\"mobile-home-dashboard\" aria-label=\"Mobile home dashboard\"><div class=\"mobile-home-card mobile-current-card\"><div class=\"mobile-home-card-head\"><span class=\"settings-status-marker ok\" aria-hidden=\"true\"></span><span class=\"mobile-home-kicker\">current session dashboard</span></div><strong id=\"mobile-home-current-title\">No session selected</strong><p id=\"mobile-home-current-copy\">Select a persisted session or create a new conversation.</p><div class=\"mobile-home-metrics\" id=\"mobile-home-current-metrics\">0 running · 0 review · 0 blocked · 0 closed</div></div><div class=\"mobile-home-grid\"><article class=\"mobile-home-card\"><div class=\"mobile-home-card-head\"><span class=\"settings-status-marker attention\" id=\"mobile-home-timer-marker\" aria-hidden=\"true\"></span><span class=\"mobile-home-kicker\">timer dashboard</span></div><strong id=\"mobile-home-timer-title\">Timer owner truth</strong><p id=\"mobile-home-timer-copy\">waiting for timer projection</p><div class=\"mobile-home-session-list\" id=\"mobile-home-timer-list\">waiting for timer truth</div></article><article class=\"mobile-home-card\"><div class=\"mobile-home-card-head\"><span class=\"settings-status-marker ok\" aria-hidden=\"true\"></span><span class=\"mobile-home-kicker\">persisted sessions</span></div><strong id=\"mobile-home-session-count\">0 sessions</strong><div class=\"mobile-home-session-list\" id=\"mobile-home-session-list\">waiting for session truth</div></article></div></section>",
            "<section class=\"mobile-agent-summary-strip\" id=\"mobile-agent-summary-strip\" aria-label=\"Agent status\">",
            "<button class=\"mobile-agent-summary-button\" id=\"open-mobile-agent-sheet-button\" type=\"button\" aria-controls=\"mobile-agent-sheet\" aria-expanded=\"false\">",
            "<span class=\"mobile-agent-summary-dot\" id=\"mobile-agent-summary-dot\" aria-hidden=\"true\"></span>",
            "<span class=\"mobile-agent-summary-content\"><span class=\"mobile-agent-summary-title\" id=\"mobile-agent-summary-title\">Agent status unavailable</span><span class=\"mobile-agent-summary-copy\" id=\"mobile-agent-summary-copy\">Waiting for Task Center truth</span></span>",
            "<span class=\"mobile-agent-summary-chevron\" aria-hidden=\"true\">⌃</span>",
            "</button>",
            "</section>",
            "<div class=\"mobile-bottom-entries\" aria-label=\"Mobile bottom quick entrances\"><button class=\"mobile-drawer-button mobile-corner-button\" id=\"mobile-new-entry-button\" type=\"button\" aria-label=\"新建会话\"><svg viewBox=\"0 0 24 24\" aria-hidden=\"true\"><path d=\"M5 6h14v9H9l-4 3V6Z\"/><path d=\"M12 8.5v4\"/><path d=\"M10 10.5h4\"/></svg></button><button class=\"mobile-drawer-button mobile-corner-button\" id=\"open-session-drawer-button\" type=\"button\" aria-label=\"搜索 session\" aria-controls=\"session-list\"><svg viewBox=\"0 0 24 24\" aria-hidden=\"true\"><circle cx=\"10.5\" cy=\"10.5\" r=\"5.8\"/><path d=\"m15 15 4.5 4.5\"/></svg></button></div>",
            "<section class=\"conversation-region region-card\">",
            "<div class=\"region-header\">",
            "<div class=\"turn-status\">",
            "<span class=\"status-dot\" id=\"turn-status\">waiting</span>",
            "</div>",
            "</div>",
            "<div class=\"stream-stage\">",
            "<div class=\"message-list autonomous\" id=\"message-list\">",
            "<div class=\"chat-empty-state\"><div class=\"chat-empty-title\">New conversation</div><div class=\"chat-empty-copy\">Send a message to start this session.</div></div>",
            "</div>",
            "</div>",
            "<section class=\"composer-card\">",
            "<form class=\"composer-grid\" id=\"composer-form\">",
            "<textarea class=\"composer-input\" id=\"composer-input\" placeholder=\"输入新的任务或继续当前 turn\"></textarea>",
            "<div class=\"composer-actions\">",
            "<button class=\"button\" id=\"send-button\" type=\"submit\">Send</button>",
            "<button class=\"button secondary\" id=\"cancel-button\" type=\"button\">Cancel</button>",
            "</div>",
            "</form>",
            "<div class=\"composer-control-strip\" aria-label=\"Composer controls\">",
            "<label class=\"control-chip\" id=\"attach-file-button\" for=\"attachment-file-input\" role=\"button\" tabindex=\"0\">加文件</label>",
            "<label class=\"control-chip\" id=\"attach-image-button\" for=\"attachment-image-input\" role=\"button\" tabindex=\"0\">加图片</label>",
            "<label class=\"control-chip\" id=\"attach-video-button\" for=\"attachment-video-input\" role=\"button\" tabindex=\"0\">加视频</label>",
            "<button class=\"control-chip\" id=\"preview-attachments-button\" type=\"button\">预览附件</button>",
            "<button class=\"control-chip\" id=\"refresh-session-button\" type=\"button\">刷新会话</button>",
            "<label class=\"cwd-control\" for=\"cwd-input\"><span>CWD</span><input id=\"cwd-input\" type=\"text\" placeholder=\"/path/to/workspace\" autocomplete=\"off\" /></label>",
            "<label class=\"model-control\" for=\"model-selector\"><span>Model</span><select id=\"model-selector\"><option value=\"runtime\">Runtime config</option></select></label>",
            "<input id=\"attachment-file-input\" type=\"file\" multiple hidden />",
            "<input id=\"attachment-image-input\" type=\"file\" accept=\"image/*\" multiple hidden />",
            "<input id=\"attachment-video-input\" type=\"file\" accept=\"video/*\" multiple hidden />",
            "</div>",
            "<div class=\"attachment-tray\" id=\"attachment-tray\" aria-live=\"polite\"></div>",
            "<div class=\"command-status\" id=\"command-status\">command idle</div>",
            "</section>",
            "</section>",
            "</section>",
            "<div class=\"layout-resizer layout-resizer-right\" data-layout-resizer=\"right\" role=\"separator\" aria-orientation=\"vertical\" aria-label=\"Resize details panel\" tabindex=\"0\"></div>",
            "<dialog class=\"new-session-dialog\" id=\"new-session-dialog\" aria-labelledby=\"new-session-dialog-title\">",
            "<form class=\"new-session-panel\" id=\"new-session-form\" method=\"dialog\">",
            "<div class=\"new-session-head\">",
            "<div><div class=\"eyebrow\">new</div><h2 class=\"new-session-title\" id=\"new-session-dialog-title\">Start work</h2></div>",
            "<button class=\"dialog-close-button\" id=\"new-session-cancel-button\" type=\"button\">Close</button>",
            "</div>",
            "<div class=\"new-session-choice\" role=\"radiogroup\" aria-label=\"New session type\">",
            "<label class=\"new-session-option\"><input type=\"radio\" name=\"new-session-kind\" value=\"conversation\" checked /><span><strong>New session</strong><small>Global conversation</small></span></label>",
            "<label class=\"new-session-option\"><input type=\"radio\" name=\"new-session-kind\" value=\"task\" /><span><strong>New task</strong><small>Choose a target directory</small></span></label>",
            "</div>",
            "<label class=\"new-task-path-control\" for=\"new-session-cwd-input\"><span>Task directory</span><div class=\"new-task-path-row\"><input id=\"new-session-cwd-input\" type=\"text\" placeholder=\"Choose or type a path\" autocomplete=\"off\" /><button class=\"control-chip\" id=\"new-session-browse-button\" type=\"button\">Choose</button></div></label>",
            "<div class=\"new-task-path-presets\" id=\"new-task-path-presets\" aria-label=\"Task directory choices\">",
            "<button class=\"path-preset-button\" type=\"button\" data-cwd=\"/Volumes/extension/code/freehand\">freehand</button>",
            "<button class=\"path-preset-button\" type=\"button\" data-cwd=\"/Volumes/extension/code\">code</button>",
            "<button class=\"path-preset-button\" type=\"button\" data-cwd=\"/Users/fanzhang/code\">~/code</button>",
            "</div>",
            "<div class=\"new-session-actions\">",
            "<button class=\"session-bulk-button\" id=\"new-session-close-button\" type=\"button\">Cancel</button>",
            "<button class=\"session-task-button\" id=\"new-session-confirm-button\" type=\"submit\">Create</button>",
            "</div>",
            "</form>",
            "</dialog>",
            "<dialog class=\"timer-dashboard-dialog\" id=\"timer-dashboard-dialog\" aria-labelledby=\"timer-dashboard-title\">",
            "<form class=\"timer-dashboard-panel\" id=\"timer-dashboard-form\" method=\"dialog\">",
            "<div class=\"new-session-head\">",
            "<div><div class=\"eyebrow\">timer</div><h2 class=\"new-session-title\" id=\"timer-dashboard-title\">Timer owner dashboard</h2></div>",
            "<button class=\"dialog-close-button\" id=\"timer-dashboard-close-button\" type=\"button\">Close</button>",
            "</div>",
            "<p class=\"settings-note\">Timers are independent runtime truth. They can wake the selected Master session later by injecting the persisted prompt as a new turn.</p>",
            "<div class=\"timer-form-grid\">",
            "<label><span>Mode</span><select id=\"timer-mode-input\"><option value=\"relative\">Relative countdown</option><option value=\"absolute\">Absolute Unix time</option><option value=\"recurring\">Recurring / cron</option></select></label>",
            "<label><span>Delay seconds</span><input id=\"timer-delay-input\" type=\"number\" min=\"1\" step=\"1\" value=\"180\" /></label>",
            "<label><span>Run at Unix seconds</span><input id=\"timer-run-at-input\" type=\"number\" min=\"0\" step=\"1\" /></label>",
            "<label><span>Repeat kind</span><select id=\"timer-repeat-kind-input\"><option value=\"interval\">Interval</option><option value=\"daily\">Daily local</option><option value=\"weekly\">Weekly local</option><option value=\"cron\">Cron</option></select></label>",
            "<label><span>Interval seconds</span><input id=\"timer-interval-input\" type=\"number\" min=\"1\" step=\"1\" value=\"300\" /></label>",
            "<label><span>Local seconds of day</span><input id=\"timer-time-of-day-input\" type=\"number\" min=\"0\" max=\"86399\" step=\"1\" value=\"32400\" /></label>",
            "<label><span>Weekdays 0..6</span><input id=\"timer-weekdays-input\" type=\"text\" value=\"1,2,3,4,5\" autocomplete=\"off\" /></label>",
            "<label><span>Cron expression</span><input id=\"timer-cron-input\" type=\"text\" value=\"*/15 9-17 * * 1-5\" autocomplete=\"off\" /></label>",
            "<label><span>Max runs</span><input id=\"timer-max-runs-input\" type=\"number\" min=\"1\" step=\"1\" value=\"1\" /></label>",
            "<label><span>Source session</span><select id=\"timer-source-session-input\"><option value=\"\">Internal wakeup</option></select></label>",
            "</div>",
            "<label class=\"timer-text-control\"><span>Reason</span><input id=\"timer-reason-input\" type=\"text\" value=\"Recheck current work\" autocomplete=\"off\" /></label>",
            "<label class=\"timer-text-control\"><span>Wakeup prompt</span><textarea id=\"timer-prompt-input\">Inspect current framework truth, then decide the next Master action.</textarea></label>",
            "<div class=\"new-session-actions\">",
            "<button class=\"session-bulk-button\" id=\"timer-dashboard-refresh-button\" type=\"button\">Refresh timers</button>",
            "<button class=\"session-task-button\" id=\"timer-dashboard-create-button\" type=\"submit\">Schedule timer</button>",
            "</div>",
            "<div class=\"settings-note\" id=\"timer-dashboard-status\">waiting for timer projection</div>",
            "<div class=\"timer-dashboard-list\" id=\"timer-dashboard-list\">waiting for timer truth</div>",
            "<div class=\"timer-dashboard-history\" id=\"timer-dashboard-history\">waiting for timer ledger</div>",
            "</form>",
            "</dialog>",
            "<aside class=\"inspector\">",
            "<div class=\"drawer-panel-head\">",
            "<div><div class=\"eyebrow\" id=\"inspector-eyebrow\">lifecycle observer</div><h2 class=\"inspector-title\" id=\"inspector-title\">Task and Agent Lifecycle</h2></div>",
            "<button class=\"drawer-close-button\" id=\"close-detail-drawer-button\" type=\"button\" aria-label=\"Close details\">Close</button>",
            "</div>",
            "<p class=\"page-copy\" id=\"inspector-copy\">观察 Master/Worker 生命周期、当前执行、事件和必要的调试摘要；活跃 Worker 会高亮并可点击查看对应任务进度。</p>",
            "<div class=\"stack inspector-debug-panel\" id=\"inspector-debug-panel\">",
            "<section class=\"inspector-block\">",
            "<div class=\"meta-label\">debug status</div>",
            "<div class=\"inspector-block-title\" id=\"debug-status\">waiting</div>",
            "<div class=\"inspector-copy\" id=\"debug-lines\">-</div>",
            "</section>",
            "<section class=\"inspector-block checkpoint-block\">",
            "<div class=\"meta-label\">checkpoints</div>",
            "<div class=\"inspector-block-title\" id=\"checkpoint-status\">waiting</div>",
            "<div class=\"checkpoint-list\" id=\"checkpoint-list\">-</div>",
            "</section>",
            "<section class=\"inspector-block phase2-board-block\">",
            "<div class=\"meta-label\">task board</div>",
            "<div class=\"inspector-block-title\" id=\"task-board-status\">waiting</div>",
            "<div class=\"phase2-list\" id=\"task-board-list\">-</div>",
            "</section>",
            "<section class=\"inspector-block phase2-board-block\">",
            "<div class=\"meta-label\">agent board</div>",
            "<div class=\"inspector-block-title\" id=\"agent-board-status\">waiting</div>",
            "<div class=\"phase2-list\" id=\"agent-board-list\">-</div>",
            "</section>",
            "<section class=\"inspector-block phase2-board-block\">",
            "<div class=\"meta-label\">event inbox</div>",
            "<div class=\"inspector-block-title\" id=\"event-inbox-status\">waiting</div>",
            "<div class=\"phase2-list\" id=\"event-inbox-list\">-</div>",
            "</section>",
            "<section class=\"inspector-block phase2-board-block\">",
            "<div class=\"meta-label\">execution history</div>",
            "<div class=\"inspector-block-title\" id=\"task-history-status\">waiting</div>",
            "<div class=\"phase2-list\" id=\"task-history-list\">-</div>",
            "</section>",
            "<section class=\"inspector-block phase2-board-block\">",
            "<div class=\"meta-label\">worker control</div>",
            "<div class=\"inspector-block-title\" id=\"worker-control-status\">waiting</div>",
            "<div class=\"phase2-list\" id=\"worker-control-list\">-</div>",
            "</section>",
            "</div>",
            "<div class=\"settings-shell\" id=\"settings-shell\" hidden>",
            "<section class=\"settings-hero\">",
            "<div><div class=\"meta-label\">editable</div><div class=\"settings-hero-title\">Provider config</div></div>",
            "<span class=\"settings-status-pill\" id=\"settings-status-pill\">connecting</span>",
            "</section>",
            "<div class=\"settings-grid\">",
            "<details class=\"settings-card\" open><summary><span>Provider registry</span><span id=\"settings-provider-summary\">loading</span></summary><div class=\"settings-card-body\">",
            "<div class=\"settings-row\"><span>Current provider</span><strong id=\"settings-provider-id\">loading</strong></div><div class=\"settings-row\"><span>Type</span><strong id=\"settings-provider-type\">loading</strong></div><div class=\"settings-row\"><span>Protocol</span><strong id=\"settings-provider-protocol\">loading</strong></div><div class=\"settings-row\"><span>Host</span><strong id=\"settings-provider-host\">loading</strong></div><div class=\"settings-row\"><span>Model selector</span><strong id=\"settings-model-value\">Runtime config</strong></div><div class=\"settings-row\"><span>Web search</span><strong id=\"settings-provider-web-search\">loading</strong></div><div class=\"settings-row\"><span>Auth source</span><strong id=\"settings-provider-auth\">loading</strong></div><div class=\"settings-row\"><span>Activation</span><strong id=\"settings-restart-required\">loading</strong></div><div class=\"settings-row\"><span>Config status</span><strong id=\"settings-config-error\">none</strong></div>",
            "<div class=\"settings-provider-switch\" id=\"settings-provider-switch\"><label><span>Primary</span><select id=\"settings-provider-current-select\"></select></label><label><span>Fallback</span><select id=\"settings-provider-fallback-select\"></select></label><button class=\"settings-primary-action\" id=\"settings-provider-switch-button\" type=\"button\">Switch provider</button><div class=\"settings-note\" id=\"settings-provider-switch-status\">Switch changes the selected agent provider; restart is required before active runtime changes.</div></div>",
            "<div class=\"settings-provider-registry\" id=\"settings-provider-registry-list\">loading provider registry</div>",
            "<form class=\"settings-provider-form\" id=\"settings-provider-form\"><label><span>Provider id</span><input id=\"settings-provider-id-input\" name=\"provider_id\" autocomplete=\"off\" /></label><label><span>Type</span><select id=\"settings-provider-type-input\" name=\"provider_type\"><option value=\"openai\">OpenAI-compatible</option><option value=\"anthropic\">Anthropic messages</option></select></label><label><span>Protocol</span><select id=\"settings-provider-protocol-input\" name=\"provider_protocol\"><option value=\"responses\">Responses</option><option value=\"chat_completions\">Chat completions</option><option value=\"messages\">Messages</option></select></label><label><span>Endpoint</span><input id=\"settings-provider-url-input\" name=\"base_url\" placeholder=\"https://api.example.com/v1\" autocomplete=\"off\" /></label><label><span>Default model</span><input id=\"settings-provider-model-input\" name=\"default_model\" autocomplete=\"off\" /></label><label><span>Web search</span><select id=\"settings-provider-web-search-input\" name=\"web_search\"><option value=\"auto\">Auto</option><option value=\"disabled\">Disabled</option></select></label><label><span>Credential env var</span><input id=\"settings-provider-env-input\" name=\"api_key_env\" placeholder=\"PROVIDER_CREDENTIAL\" autocomplete=\"off\" /></label><div class=\"settings-note\" id=\"settings-provider-save-status\">Add or update one provider definition with env-var auth. Use Switch provider to change the selected agent binding.</div><div class=\"settings-note\" id=\"settings-provider-web-search-test-status\">Provider web_search test has not run.</div><button class=\"settings-primary-action\" id=\"settings-provider-save-button\" type=\"submit\">Add/update provider</button><button class=\"settings-secondary-action\" id=\"settings-provider-web-search-test-button\" type=\"button\">Test web_search</button></form></div></details>",
            "<details class=\"settings-card\" open><summary><span>Model groups</span><span id=\"settings-model-group-summary\">loading</span></summary><div class=\"settings-card-body\"><div class=\"settings-model-group-switch\" id=\"settings-model-group-switch\"><label><span>Active group</span><select id=\"settings-model-group-current-select\"></select></label><button class=\"settings-primary-action\" id=\"settings-model-group-switch-button\" type=\"button\">Switch group</button><div class=\"settings-note\" id=\"settings-model-group-switch-status\">Model group selection changes the selected agent primary/fallback model routes; restart is required before active runtime changes.</div></div><div class=\"settings-model-group-registry\" id=\"settings-model-group-registry-list\">loading model groups</div><form class=\"settings-model-group-form\" id=\"settings-model-group-form\"><label><span>Group id</span><input id=\"settings-model-group-id-input\" name=\"group_id\" autocomplete=\"off\" /></label><label><span>Label</span><input id=\"settings-model-group-label-input\" name=\"label\" autocomplete=\"off\" /></label><label class=\"settings-inline-check\"><input id=\"settings-model-group-enabled-input\" name=\"enabled\" type=\"checkbox\" checked /><span>Enabled</span></label><label><span>Primary provider</span><select id=\"settings-model-group-primary-provider-input\"></select></label><label><span>Primary model</span><input id=\"settings-model-group-primary-model-input\" autocomplete=\"off\" /></label><label><span>Sub provider</span><select id=\"settings-model-group-sub-provider-input\"></select></label><label><span>Sub model</span><input id=\"settings-model-group-sub-model-input\" autocomplete=\"off\" /></label><label><span>Search provider</span><select id=\"settings-model-group-search-provider-input\"></select></label><label><span>Search model</span><input id=\"settings-model-group-search-model-input\" autocomplete=\"off\" /></label><label><span>Title provider</span><select id=\"settings-model-group-title-provider-input\"></select></label><label><span>Title model</span><input id=\"settings-model-group-title-model-input\" autocomplete=\"off\" /></label><label><span>Fallback provider</span><select id=\"settings-model-group-fallback-provider-input\"></select></label><label><span>Fallback model</span><input id=\"settings-model-group-fallback-model-input\" autocomplete=\"off\" /></label><label><span>Load balance</span><input id=\"settings-model-group-load-balance-input\" placeholder=\"provider:model:weight, provider:model:weight\" autocomplete=\"off\" /></label><div class=\"settings-note\" id=\"settings-model-group-save-status\">Add or update one model group. Optional routes require both provider and model.</div><button class=\"settings-primary-action\" id=\"settings-model-group-save-button\" type=\"submit\">Add/update model group</button></form></div></details>",
            "<details class=\"settings-card\" open><summary><span>Worker limit</span><span id=\"settings-agent-resource-summary\">loading</span></summary><div class=\"settings-card-body\"><div class=\"settings-row\"><span>Provider mode</span><strong id=\"settings-agent-resource-provider\">loading</strong></div><div class=\"settings-agent-resource-control\"><button id=\"settings-agent-resource-decrement\" type=\"button\" aria-label=\"Decrease Worker limit\">−</button><strong id=\"settings-agent-resource-count\">1</strong><span>max <span id=\"settings-agent-resource-limit\">5</span></span><button id=\"settings-agent-resource-increment\" type=\"button\" aria-label=\"Increase Worker limit\">+</button></div><div class=\"settings-note\" id=\"settings-agent-resource-status\">Config truth loads from the active Master.</div><button class=\"settings-primary-action\" id=\"settings-agent-resource-save\" type=\"button\">Save Worker limit</button></div></details>",
            "<details class=\"settings-card\" open><summary><span>Android APK update</span><span id=\"settings-apk-update-summary\">Android app only</span></summary><div class=\"settings-card-body\"><div class=\"settings-row\"><span>Update source</span><strong id=\"settings-apk-update-source\">daemon /android/update.json</strong></div><div class=\"settings-note\" id=\"settings-apk-update-status\">Open this Settings page inside the Android app to check and download a newer APK.</div><button class=\"settings-primary-action\" id=\"settings-apk-update-check-button\" type=\"button\">Check APK update</button></div></details>",
            "<section class=\"settings-review-tree\" id=\"settings-review-tree\" aria-label=\"Phase 1 settings tree\"></section>",
            "</div>",
            "</div>",
            "</aside>",
            "<section class=\"mobile-agent-sheet\" id=\"mobile-agent-sheet\" role=\"dialog\" aria-modal=\"true\" aria-hidden=\"true\" aria-labelledby=\"mobile-agent-sheet-title\">",
            "<div class=\"mobile-agent-sheet-handle\" aria-hidden=\"true\"></div>",
            "<header class=\"mobile-agent-sheet-header\"><div><div class=\"eyebrow\">current session</div><h2 class=\"mobile-agent-sheet-title\" id=\"mobile-agent-sheet-title\">Agents</h2></div><button class=\"drawer-close-button\" id=\"close-mobile-agent-sheet-button\" type=\"button\" aria-label=\"Close Agents\">Close</button></header>",
            "<div class=\"mobile-agent-sheet-scroll\">",
            "<section class=\"mobile-agent-section\"><div class=\"mobile-agent-section-head\"><div><div class=\"mobile-agent-card-kicker\">Worker tasks</div><h3>Tap a task to open its Worker conversation</h3></div><span id=\"mobile-agent-task-status\">waiting</span></div><div class=\"mobile-agent-list\" id=\"mobile-agent-task-list\"></div></section>",
            "</div>",
            "</section>",
            "</main>",
            "<script type=\"module\" src=\"/assets/webui.js?v=20260724-model-groups-ui\"></script>",
            "</body>",
            "</html>"
        ),
        initial_body_attrs, initial_shell_attrs
    )
}

fn initial_layout_body_attrs(client: Option<&str>) -> &'static str {
    match client {
        Some(ANDROID_WEBVIEW_CLIENT) => ANDROID_WEBVIEW_INITIAL_LAYOUT_ATTRS,
        _ => "",
    }
}

fn initial_layout_shell_attrs(client: Option<&str>) -> &'static str {
    match client {
        Some(ANDROID_WEBVIEW_CLIENT) => ANDROID_WEBVIEW_INITIAL_LAYOUT_ATTRS,
        _ => "",
    }
}
